name: Build and Deploy

on:
  push:
    branches:
      - harshita_feature-test#24
      - release-candidate-*
  create:
    tags:
      - 'v*'
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-app
  NAMESPACE: scilifelab-traininghub-platform

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Determine the environment
      id: determine-env
      run: |
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/heads/harshita_feature-* ]]; then
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "VARIABLE_VALUE=${{ secrets.DEV_BASE_URL }}" >> $GITHUB_ENV
        elif [[ "${{ github.event_name }}" == "create" && "${{ github.ref_type }}" == "tag" ]]; then
          echo "ENVIRONMENT=preprod" >> $GITHUB_ENV
          echo "VARIABLE_VALUE=${{ secrets.PREPROD_BASE_URL }}" >> $GITHUB_ENV
        elif [[ "${{ github.event_name }}" == "release" && "${{ github.event.action }}" == "published" ]]; then
          echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          echo "VARIABLE_VALUE=${{ secrets.PROD_BASE_URL }}" >> $GITHUB_ENV
        fi

    - name: Change base_url in config/tess.yml
      run: |
        sed -i 's|base_url: .*|base_url: '${{ env.VARIABLE_VALUE }}'|' config/tess.yml

    - name: Set lowercase repository name
      id: lowercase-repo
      run: |
        REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | awk -F/ '{print tolower($2)}')
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)
        docker build -t ghcr.io/${{ env.NAMESPACE }}/${{ env.REPO_NAME }}-app-${{ env.ENVIRONMENT }}:$IMAGE_TAG .
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Log in to the container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ env.NAMESPACE }}/${{ env.REPO_NAME }}-app-${{ env.ENVIRONMENT }}:${{ env.IMAGE_TAG }}
